set -g status-bg                          "default"
set -gq @thm_bar_bg                       "default"

set -gq @thm_bg                           "default"
set -gq @thm_fg                           "#dce6f2"
set -gq @thm_primary                      "#8bd5ff"
set -gq @thm_inverse_primary              "#1c1f27"
set -gq @thm_surface_low                  "#0a0c10"
set -gq @thm_surface                      "#101218"
set -gq @thm_surface_variant              "#1c1f27"
set -gq @thm_outline                      "#4b5566"
set -gq @thm_text_variant                 "#9aa9b8"

set -g status-style                       "bg=#{@thm_bg},fg=#{@thm_fg}"
set -g window-active-style                "bg=#{@thm_bg},fg=#{@thm_fg}"
