[color]
background = 'default'
foreground = '#ffb2bc'

; gradient = 0
gradient = 1
gradient_color_1 = '#72333e'
gradient_color_2 = '#ffb2bc'
gradient_color_3 = '#ffd9dd'

horizontal_gradient = 0
; horizontal_gradient = 1
horizontal_gradient_color_1 = '#72333e'
horizontal_gradient_color_2 = '#ffb2bc'
horizontal_gradient_color_3 = '#ffd9dd'
horizontal_gradient_color_4 = '#ffb2bc'
horizontal_gradient_color_5 = '#72333e'

