cursor                #ffb787
cursor_text_color     #502400

foreground            #f0dfd7
background            #140d08

selection_foreground  #502400
selection_background  #ffb787

url_color             #caca93

active_border_color   #9f8d83
inactive_border_color #140d08

tab_bar_background    #140d08
active_tab_foreground #f0dfd7
active_tab_background #312823
inactive_tab_foreground #d7c3b8
inactive_tab_background #140d08

color0  #312823
color8  #9f8d83

color1  #ffb4ab
color9  #ffb4ab

color2  #81C784
color10 #A5D6A7

color3  #FFE082
color11 #FFF59D

color4  #ffb787
color12 #6e390e

color5  #caca93
color13 #48491f

color6  #e5bfa8
color14 #5b4130

color7  #f0dfd7
color15 #d7c3b8