cursor                #80d4da
cursor_text_color     #00373a

foreground            #dde4e4
background            #090f10

selection_foreground  #00373a
selection_background  #80d4da

url_color             #b6c7ea

active_border_color   #899393
inactive_border_color #090f10

tab_bar_background    #090f10
active_tab_foreground #dde4e4
active_tab_background #252b2c
inactive_tab_foreground #bec8c9
inactive_tab_background #090f10

color0  #252b2c
color8  #899393

color1  #ffb4ab
color9  #ffb4ab

color2  #81C784
color10 #A5D6A7

color3  #FFE082
color11 #FFF59D

color4  #80d4da
color12 #004f53

color5  #b6c7ea
color13 #374764

color6  #b1cccd
color14 #324b4d

color7  #dde4e4
color15 #bec8c9