cursor                #ffb2bc
cursor_text_color     #561d28

foreground            #f0dedf
background            #140c0d

selection_foreground  #561d28
selection_background  #ffb2bc

url_color             #eabf8f

active_border_color   #9f8c8e
inactive_border_color #140c0d

tab_bar_background    #140c0d
active_tab_foreground #f0dedf
active_tab_background #312828
inactive_tab_foreground #d7c1c3
inactive_tab_background #140c0d

color0  #312828
color8  #9f8c8e

color1  #ffb4ab
color9  #ffb4ab

color2  #81C784
color10 #A5D6A7

color3  #FFE082
color11 #FFF59D

color4  #ffb2bc
color12 #72333e

color5  #eabf8f
color13 #5e411c

color6  #e5bdc0
color14 #5c3f43

color7  #f0dedf
color15 #d7c1c3