set -g @catppuccin_status_background "#140c0d"
set -g status-bg "#140c0d"
set -g @catppuccin_window_default_color "#312828"
set -g @catppuccin_window_default_background "#140c0d"
set -g @catppuccin_window_default_fill "number"
set -g @catppuccin_window_current_color "#ffb2bc"
set -g @catppuccin_window_current_background "#140c0d"
set -g @catppuccin_window_current_fill "number"
set -g @catppuccin_directory_color "#e5bdc0"
set -g @catppuccin_date_time_color "#ffb2bc"
set -g @catppuccin_session_color "#eabf8f"
set -g pane-active-border-style "fg=#ffb2bc"
set -g pane-border-style "fg=#9f8c8e"