set -g @catppuccin_status_background "#140c0e"
set -g status-bg "#140c0e"
set -g @catppuccin_window_default_color "#31282a"
set -g @catppuccin_window_default_background "#140c0e"
set -g @catppuccin_window_default_fill "number"
set -g @catppuccin_window_current_color "#ffb1c5"
set -g @catppuccin_window_current_background "#140c0e"
set -g @catppuccin_window_current_fill "number"
set -g @catppuccin_directory_color "#e3bdc5"
set -g @catppuccin_date_time_color "#ffb1c5"
set -g @catppuccin_session_color "#eebd93"
set -g pane-active-border-style "fg=#ffb1c5"
set -g pane-border-style "fg=#9e8c90"