set -g @catppuccin_status_background "#140d08"
set -g status-bg "#140d08"
set -g @catppuccin_window_default_color "#312823"
set -g @catppuccin_window_default_background "#140d08"
set -g @catppuccin_window_default_fill "number"
set -g @catppuccin_window_current_color "#ffb787"
set -g @catppuccin_window_current_background "#140d08"
set -g @catppuccin_window_current_fill "number"
set -g @catppuccin_directory_color "#e5bfa8"
set -g @catppuccin_date_time_color "#ffb787"
set -g @catppuccin_session_color "#caca93"
set -g pane-active-border-style "fg=#ffb787"
set -g pane-border-style "fg=#9f8d83"