# Colors
$background = rgba(111111ff)
$text = rgba(eeeeeeff)
$accent = rgba(00ff99ee)
$error = rgba(ff0066ee)

general {
    ignore_empty_input = true
    hide_cursor = true
}

background {
    monitor =
    path = screenshot
    blur_passes = 2
    blur_size = 6
    contrast = 1.1
    brightness = 0.9
}

input-field {
    monitor =
    size = 250, 50
    outline_thickness = 1
    dots_size = 0.3
    dots_spacing = 0.2
    dots_center = true
    
    outer_color = $accent
    inner_color = rgba(0, 0, 0, 0.2)
    font_color = $text
    
    fade_on_empty = true
    rounding = 32
    placeholder_text = <i>Password...</i>
    
    position = 0, -50
    halign = center
    valign = center
    
    fail_color = $error
    fail_text = <i>Incorrect ($ATTEMPTS)</i>
}

# Clock
label {
    monitor =
    text = cmd[update:1000] echo "$TIME"
    color = $text
    font_size = 64
    font_family = Fira Sans SemiBold
    position = 0, 100
    halign = center
    valign = center
}

# Username
label {
    monitor =
    text = $USER
    color = $text
    font_size = 20
    font_family = Fira Sans
    position = 0, 40
    halign = center
    valign = center
}
