-- Generated by nwg-displays on 2026-01-24 at 16:54:59.

hl.monitor({
    output   = "eDP-1",
    mode     = "1366x768@60.02",
    position = "3393x1056",
    scale    = 1.0,
    mirror   = "HDMI-A-1",
})

-- hl.monitor({
--     output   = "HDMI-A-1",
--     mode     = "1920x1080@60.0",
--     position = "3101x895",
--     scale    = 1.0,
--     mirror   = "eDP-1",
-- })