
#----------------------------------------------------------
#    _____                .__  __                       
#   /     \   ____   ____ |__|/  |_  ___________  ______
#  /  \ /  \ /  _ \ /    \|  \   __\/  _ \_  __ \/  ___/
# /    Y    (  <_> )   |  \  ||  | (  <_> )  | \/\___ \ 
# \____|__  /\____/|___|  /__||__|  \____/|__|  /____  >
#         \/            \/                           \/ 
#
#----------------------------------------------------------


monitor=e-DP1,preferred,auto,auto
