# : Manager [[[

[manager]
cwd = { fg = "#e1e2e8" }

# Tab
tab_active = { fg = "#00325b", bg = "#a2c9fe", bold = true }
tab_inactive = { fg = "#d2e4ff", bg = "#001c38" }
tab_width = 1

# Find
find_keyword = { fg = "#ffb4ab", bold = true, italic = true, underline = true }
find_position = { fg = "#ffb4ab", bold = true, italic = true }

# Marker
marker_copied = { fg = "#d673ff", bg = "#d673ff" }
marker_cut = { fg = "#f4d9ff", bg = "#f4d9ff" }
marker_marked = { fg = "#ffb4ab", bg = "#ffb4ab" }
marker_selected = { fg = "#d8bde4", bg = "#d8bde4" }

# Count
count_copied = { fg = "#261431", bg = "#f4d9ff" }
count_cut = { fg = "#261431", bg = "#f4d9ff" }
count_selected = { fg = "#00325b", bg = "#d8bde4" }

# Border
border_symbol = "│"
border_style = { fg = "#a2c9fe" }

# : ]]]


# : Status [[[

[status]
separator_open = "🭁"
separator_close = "🭠"
separator_style = { bg = "#00325b", fg = "#F4A261" }

[mode]
# Mode
normal_main = { bg = "#a2c9fe", fg = "#00325b", bold = true }
normal_alt = { bg = "#43474e", fg = "#c3c6cf" }

# Select mode
select_main = { bg = "#bbc7db", fg = "#263141", bold = true }
select_alt = { bg = "#43474e", fg = "#c3c6cf" }

# Unset mode
unset_main = { bg = "#d8bde4", fg = "#3c2947", bold = true }
unset_alt = { bg = "#43474e", fg = "#c3c6cf" }

# Progress
progress_label = { bold = true }
progress_normal = { fg = "#a2c9fe", bg = "#37393e" }
progress_error = { fg = "#ffb4ab", bg = "#37393e" }

# Permissions
permissions_t = { fg = "#5875a5" }
permissions_w = { fg = "#9850b8" }
permissions_x = { fg = "#ff2b12" }
permissions_r = { fg = "#c840ff" }
permissions_s = { fg = "#3988ff" }

# : ]]]


# : Select [[[

[select]
border = { fg = "#a2c9fe" }
active = { fg = "#d8bde4", bold = true }
inactive = {}

# : ]]]


# : Input [[[

[input]
border = { fg = "#a2c9fe" }
value = { fg = "#e1e2e8" }

# : ]]]


# : Completion [[[

[completion]
border = { fg = "#a2c9fe", bg = "#00325b" }

# : ]]]


# : Tasks [[[

[tasks]
border = { fg = "#a2c9fe" }
title = {}
hovered = { fg = "#f4d9ff", underline = true }

# : ]]]


# : Which [[[

[which]
cols = 3
mask = { bg = "#37393e" }
cand = { fg = "#a2c9fe" }
rest = { fg = "#00325b" }
desc = { fg = "#e1e2e8" }
separator = " ▶ "
separator_style = { fg = "#e1e2e8" }

# : ]]]


# : Help [[[

[help]
on = { fg = "#e1e2e8" }
run = { fg = "#e1e2e8" }
footer = { fg = "#263141", bg = "#bbc7db" }

# : ]]]


# : Notify [[[

[notify]
title_info = { fg = "#d8bde4" }
title_warn = { fg = "#a2c9fe" }
title_error = { fg = "#ffb4ab" }

# : ]]]


# : File-specific styles [[[

[filetype]

rules = [
    # Images
    { mime = "image/*", fg = "#94e2d5" },

    # Media
    { mime = "{audio,video}/*", fg = "#f9e2af" },

    # Archives
    { mime = "application/{zip,rar,7z*,tar,gzip,xz,zstd,bzip*,lzma,compress,archive,cpio,arj,xar,ms-cab*}", fg = "#f5c2e7" },

    # Documents
    { mime = "application/{pdf,doc,rtf}", fg = "#a6e3a1" },

    # Special files
    { name = "*", is = "orphan", bg = "#93000a" },
    { name = "*", is = "exec", fg = "#ffdad6" },

    # Fallback
    { name = "*", fg = "#e1e2e8" },
    { name = "*/", fg = "#a2c9fe" },
]

# : ]]]
