# -----------------------------------------------------
# Ryo Transparent Theme Variables
# -----------------------------------------------------

# Active Border: cool glass highlight
$outline = rgb(8bd5ff) rgb(c7a8ff) 45deg

# Inactive Border: muted translucent steel
$outline_variant = rgba(8497aa66)

# Primary/Shadow Color
$primary = rgb(8bd5ff)
